{% set data = load_setup_py_data() %}

package:
  name: DSGRN
  version: {{ data['version'] }}

source:
  path: ../src/DSGRN

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - git
    - cmake
  host:
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - graphviz
    - progressbar2
    - pychomp2

about:
  home: {{ data['url'] }}
  license: MIT
  # license: {{ data['license'] }}
  license_file: LICENSE
  summary: {{ data['description'] }}
