# Build and publish Conda packages
name: Build and publish Conda packages

on:
  push:
    branches:
      - master
    tags:
      - v* # Push events to v* tags
  workflow_dispatch:

jobs:    
  build_publish_conda:
    name: Conda pacakges for Linux, macOS and Windows
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build and publish conda packages
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'win osx linux'
      # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
